name = "fortune-backend"
main = "src/index.js"
compatibility_date = "2025-11-10"

[[kv_namespaces]]
binding = "FORTUNE_KV"
id = "c1e52a0dd0ca4605980fca3060908509"

[vars]
ENV = "dev"
DEBUG = true

[dev]
port = 8787
local_protocol = "http"
